title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

theme: unified-docs-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

collections:
  category:
    output: true
    permalink: /categories/:slugified_categories:output_ext

unified-docs-theme:
  nav_pages:
    - page: index.md
      children:
        - title: Unclickable Child
        - page: _category/test.md
    - javadoc: test-library
    - title: Not Clickable
    - title: Google
      permalink: https://google.com/
  javadoc:
    test-library:
      title: Test Library
      path: ../javadoc/build/docs/javadoc/